# Generated by Django 3.2 on 2022-08-31 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_category_clothes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothes',
            options={'verbose_name_plural': 'Clothes'},
        ),
    ]
