# Generated by Django 3.2.15 on 2022-09-16 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0012_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='clothes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clothes.clothes'),
        ),
    ]
