# Generated by Django 3.2.15 on 2022-09-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0014_auto_20220917_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='sale_price',
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
