# Generated by Django 3.2.15 on 2022-09-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0015_auto_20220917_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='percent_off',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.DeleteModel(
            name='ItemReview',
        ),
    ]
